// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6RAWF0JR43OhYoKSlEhBFRT8SMRDEFiI',
    appId: '1:855451027828:web:782e171f58e8e84a514421',
    messagingSenderId: '855451027828',
    projectId: 'extrack-ac660',
    authDomain: 'extrack-ac660.firebaseapp.com',
    storageBucket: 'extrack-ac660.appspot.com',
    measurementId: 'G-1X2DLW6BQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLXlJHIqgrVQSf5IyY4Pw_AY26fXK5lu0',
    appId: '1:855451027828:android:159fd584263bd07e514421',
    messagingSenderId: '855451027828',
    projectId: 'extrack-ac660',
    storageBucket: 'extrack-ac660.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBh3Mf5RClopBe1hVLndbf_NGkTfylVlY',
    appId: '1:855451027828:ios:cf5e14930f0a2c76514421',
    messagingSenderId: '855451027828',
    projectId: 'extrack-ac660',
    storageBucket: 'extrack-ac660.appspot.com',
    iosClientId: '855451027828-uiv2uf9cmufdrpck67oude39bovouj56.apps.googleusercontent.com',
    iosBundleId: 'com.example.extrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBh3Mf5RClopBe1hVLndbf_NGkTfylVlY',
    appId: '1:855451027828:ios:cf5e14930f0a2c76514421',
    messagingSenderId: '855451027828',
    projectId: 'extrack-ac660',
    storageBucket: 'extrack-ac660.appspot.com',
    iosClientId: '855451027828-uiv2uf9cmufdrpck67oude39bovouj56.apps.googleusercontent.com',
    iosBundleId: 'com.example.extrack',
  );
}
